## Assignement 1 Questions 1 to 6

## 1. Create a null vector of size 10 but the fifth value which is 1.

In [2]:
import numpy as np

z = np.zeros(10)
z[4] = 1
z

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

## 2. Create a vector with values ranging from 10 to 49.

In [3]:
r = np.arange(10,50)
r

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## 3. Create a 3x3 matrix with values ranging from 0 to 8

In [4]:
mat = np.arange(0,9).reshape(3,1,3)
mat

array([[[0, 1, 2]],

       [[3, 4, 5]],

       [[6, 7, 8]]])

## 4. Find indices of non-zero elements from [1,2,0,0,4,0]

In [8]:
arr = [1,2,0,0,4,0]
# for i in range(len(arr)-1):
#     if arr[i]!=0:
#         print(i)

nonzero = np.nonzero(arr)
nonzero

(array([0, 1, 4], dtype=int64),)

## 5. Create a 10x10 array with random values and find the minimum and maximum values.

In [16]:
import random
arr = np.random.randint((100),size = (10,10))
print(arr)
min = arr.min()
max = arr.max()
print("Maximum Values : ",max)
print("Minimum Values : ",min )

[[73 51 14 52 98 18 61 64 31 30]
 [95 65 12 10  5 79 75 43 72 93]
 [37 78 33  5  8 74 36 63 89 84]
 [78 80 93 78 19 30 88 72 84 62]
 [ 7  3 46 17 31 86 48 43 72 45]
 [28 49 66 53 47 10 27 68 62  0]
 [28  6 21 35 45 93 22 58 24 12]
 [80  8  4 96 30 55 63 62 17 66]
 [50 98 98 65 37  2  0 67 32  5]
 [35 43 78  3 83 10 56 14 28 58]]
Maximum Values :  98
Minimum Values :  0
